'use client'

import { useState, useEffect } from 'react'
import Link from 'next/link'
import { useParams } from 'next/navigation'
import { AuthGuard } from '@/components/auth-guard'
import { NavigationHeader } from '@/components/navigation-header'
import { SuccessCheckmark } from '@/components/success-checkmark'
import { ScrollReveal } from '@/components/scroll-reveal'
import { DynamicBackground } from '@/components/dynamic-background'
import { GitHubIcon, GitHubPRBadge, GitHubBranchBadge } from '@/components/github-icon'
import { api } from '@/lib/api'

function buildAuditLog(job: any, result: any, repo: any): string {
  const si = result?.structured_intent || {}
  const impact = si.impact_report || {}
  const changes = result?.change_set || result?.changes || []

  let log = `[ThinkSync Audit Trail]
Intent: "${job?.intent_text || 'N/A'}"
Timestamp: ${job?.created_at || new Date().toISOString()}
Repository: ${repo?.full_name || 'N/A'}

== Analysis Summary ==
Risk score: ${(si.risk_level || si.estimated_risk || 'medium').toUpperCase()}
Action type: ${si.action_type || 'modify'}

== Impact ==
Direct changes: ${impact.direct_changes || changes.length}
First-degree callers: ${impact.first_degree_callers || 'N/A'}
Transitive dependencies: ${impact.transitive_deps || 'N/A'}

== Files Modified ==\n`

  changes.forEach((c: any, i: number) => {
    const emoji = c.change_type === 'add' ? '(NEW)' : c.change_type === 'delete' ? '(DEL)' : '(MOD)'
    log += `${i + 1}. ${c.file_path} ${emoji}\n`
    if (c.justification) log += `   - ${c.justification}\n`
  })

  log += `
== Summary ==
${si.change_summary || result?.summary || 'AI-generated code changes.'}

---
Generated by ThinkSync — AI-native codebase intelligence`

  return log
}

function PRContent() {
  const params = useParams()
  const repoId = params.id as string
  const prId = params.prId as string

  const [showStats, setShowStats] = useState(false)
  const [isAuditExpanded, setIsAuditExpanded] = useState(false)
  const [isLoading, setIsLoading] = useState(true)
  const [jobData, setJobData] = useState<any>(null)
  const [result, setResult] = useState<any>(null)
  const [repoInfo, setRepoInfo] = useState<any>(null)
  const [auditLog, setAuditLog] = useState('')

  useEffect(() => {
    async function load() {
      try {
        const data = await api.analyze.getResult(prId)
        setJobData(data.job)
        setResult(data.result)
        setRepoInfo(data.repo)
        setAuditLog(buildAuditLog(data.job, data.result, data.repo))
      } catch (err) {
        console.error('Failed to load PR data:', err)
      } finally {
        setIsLoading(false)
      }
    }
    load()
  }, [prId])

  const changes = result?.change_set || result?.changes || []
  const addedLines = changes.reduce((acc: number, c: any) => acc + (c.new_code || '').split('\n').length, 0)
  const removedLines = changes.reduce((acc: number, c: any) => acc + (c.original_code || '').split('\n').length, 0)
  const prUrl = jobData?.pr_url || result?.pr_url
  const prNumber = jobData?.pr_number || result?.pr_number

  if (isLoading) {
    return (
      <div className="min-h-screen bg-ts-base flex items-center justify-center">
        <div className="w-8 h-8 border-2 border-ts-emerald border-t-transparent rounded-full animate-spin" />
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-ts-base relative">
      <div className="fixed inset-0 z-0 opacity-40">
        <DynamicBackground />
      </div>

      <NavigationHeader currentPath={`~/${repoInfo?.full_name || 'repo'}/pr/${prNumber || ''}`} />

      <main className="relative z-10 pt-12 min-h-screen flex flex-col items-center justify-center px-4">
        {/* Success State */}
        <div className="text-center mb-8">
          <SuccessCheckmark
            size={80}
            onComplete={() => setShowStats(true)}
          />

          <div
            className="mt-6 transition-all duration-200"
            style={{
              opacity: showStats ? 1 : 0,
              transform: showStats ? 'translateY(0)' : 'translateY(8px)',
            }}
          >
            <div className="flex items-center justify-center gap-2 mb-3">
              <GitHubIcon size={18} className="text-ts-text-muted" />
              <p className="font-mono text-[12px] text-ts-text-muted">
                {prUrl ? 'Pull Request Created' : 'Analysis Complete'}
              </p>
            </div>

            {prNumber && (
              <div className="flex items-center justify-center gap-3">
                <GitHubPRBadge number={prNumber} status="open" />
                <GitHubBranchBadge branch="thinksync/changes" />
              </div>
            )}

            <p className="mt-3 font-mono text-[11px] text-ts-text-dim">
              {repoInfo?.full_name}
            </p>
          </div>
        </div>

        {/* Stats */}
        <div
          className="flex items-center gap-8 mb-8 transition-all duration-300"
          style={{
            opacity: showStats ? 1 : 0,
            transform: showStats ? 'translateY(0)' : 'translateY(12px)',
            transitionDelay: '200ms',
          }}
        >
          <div className="text-center">
            <p className="font-mono text-[24px] font-medium text-ts-text-secondary">{changes.length}</p>
            <p className="font-mono text-[9px] text-ts-text-dim uppercase tracking-wider">Files Changed</p>
          </div>
          <div className="text-center">
            <p className="font-mono text-[24px] font-medium text-ts-emerald">+{addedLines}</p>
            <p className="font-mono text-[9px] text-ts-text-dim uppercase tracking-wider">Lines Added</p>
          </div>
          <div className="text-center">
            <p className="font-mono text-[24px] font-medium text-ts-red">-{removedLines}</p>
            <p className="font-mono text-[9px] text-ts-text-dim uppercase tracking-wider">Lines Removed</p>
          </div>
        </div>

        {/* Primary Action */}
        <div
          className="mb-16 transition-all duration-300"
          style={{
            opacity: showStats ? 1 : 0,
            transform: showStats ? 'translateY(0)' : 'translateY(12px)',
            transitionDelay: '400ms',
          }}
        >
          {prUrl ? (
            <a
              href={prUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="group inline-flex items-center gap-2 font-mono text-[10px] text-ts-text-primary bg-ts-surface border border-ts-border px-4 py-2 rounded hover:border-ts-emerald hover:text-ts-emerald transition-all"
            >
              <GitHubIcon size={14} className="group-hover:scale-110 transition-transform" />
              View on GitHub
              <svg className="w-3 h-3 opacity-50 group-hover:opacity-100 transition-opacity" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14" />
              </svg>
            </a>
          ) : (
            <Link
              href={`/repo/${repoId}/plan/${prId}`}
              className="font-mono text-[10px] text-ts-emerald border border-ts-emerald px-4 py-2 rounded hover:bg-ts-emerald-dim transition-colors"
            >
              View Change Plan
            </Link>
          )}
        </div>

        {/* Audit Trail */}
        <ScrollReveal className="w-full max-w-2xl">
          <div className="border-t border-ts-border pt-8">
            <button
              onClick={() => setIsAuditExpanded(!isAuditExpanded)}
              className="w-full flex items-center justify-between mb-4"
            >
              <span className="font-mono text-[9px] uppercase tracking-wider text-ts-text-dim">
                Full Audit Trail
              </span>
              <span className="font-mono text-[10px] text-ts-text-ghost">
                {isAuditExpanded ? '− Collapse' : '+ Expand'}
              </span>
            </button>

            <div
              className={`overflow-hidden transition-all duration-300 ${
                isAuditExpanded ? 'max-h-[2000px]' : 'max-h-0'
              }`}
            >
              <pre className="bg-ts-surface border border-ts-border rounded p-4 font-mono text-[9px] text-ts-text-muted overflow-x-auto whitespace-pre-wrap">
                {auditLog}
              </pre>
            </div>
          </div>
        </ScrollReveal>

        {/* Navigation */}
        <div className="mt-12 flex items-center gap-6">
          <Link
            href="/dashboard"
            className="font-mono text-[9px] text-ts-text-dim hover:text-ts-text-muted transition-colors"
          >
            ← Back to Dashboard
          </Link>
          <Link
            href={`/repo/${repoId}/intent`}
            className="font-mono text-[9px] text-ts-emerald hover:text-ts-emerald/80 transition-colors"
          >
            New Intent →
          </Link>
        </div>
      </main>
    </div>
  )
}

export default function PRSuccessPage() {
  return (
    <AuthGuard>
      <PRContent />
    </AuthGuard>
  )
}
